# Force OS X.
language: objective-c

matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: system

before_install:
    - brew update
    - brew tap drolando/deadsnakes

install:
    # Install homebrew Pythons to make sure we're
    # not conflicting with them
    - brew install python
    - brew install python3

    - brew install python26
    - brew install python27
    - brew install python31
    - brew install python32
    - brew install python33
    - brew install python34

script:
    # Test homebrew Pythons to make sure we're
    # not conflicting with them
    - brew test python
    - brew test python3

    - brew test python26
    - brew test python27
    - brew test python31
    - brew test python32
    - brew test python33
    - brew test python34
